<?php

module_load_include('php', 'platform', 'node_fun');

/**
 * Trendlier platform hooks for Drupal
 */

function platform_menu()
{
    return array(
        'platform/add_category_form' => array(
            'title' => 'Add Category',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('platform_add_category_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        ),
    );
}

function platform_add_category_form($form, &$form_state)
{
    return array(
        'add' => array(
            '#type' => 'fieldset',
            '#title' => t('Add a category to Trendlier app'),
            'name' => array(
                '#type' => 'textfield',
                '#title' => t('Name'),
                '#required' => TRUE,
                '#default_value' => '',
                '#description' => 'Name of category',
                '#size' => 20,
                '#maxlength' => 20,
            ),
            'submit' => array(
                '#type' => 'submit',
                '#value' => 'Add',
            ),
        ),
    );
}

function platform_add_category_form_submit($form, &$form_state)
{
    try
    {
        db_set_active('platform');

        $id = db_insert('category')
            ->fields(array(
                'name' => $form_state['values']['name'],
            ))
            ->execute();

        db_set_active();

        drupal_set_message(
            'Added ' . $form_state['values']['name'] . ' ' .
            '(ID ' . $id . ')');
    }
    catch (Exception $e)
    {
        drupal_set_message($e->getMessage(), 'error');
    }
}

function platform_insert_news_post($node)
{
    if ($node->type != 'news_post')
    {
        return;
    }

    db_set_active('platform');

    $id = db_insert('news_post')
        ->fields(array(
            
        ))
        ->execute();

    db_set_active();

    return $id;
}

function platform_node_insert($node)
{
    try
    {
        platform_node_insert_news_post($node);
    }
    catch (Exception $e)
    {
        drupal_set_message($e->getMessage(), 'error');
    }
}
