<?php

module_load_include('php', 'platform', 'dao_category');
module_load_include('php', 'platform', 'dao_product');
module_load_include('php', 'platform', 'node_fun');

/**
 * Trendlier platform hooks for Drupal
 */

function platform_menu()
{
    return array(
        'platform/add_category_form' => array(
            'title' => 'Add Category',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('platform_add_category_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        ),
    );
}

function platform_add_category_form($form, &$form_state)
{
    return array(
        'add' => array(
            '#type' => 'fieldset',
            '#title' => t('Add a category to Trendlier app'),
            'name' => array(
                '#type' => 'textfield',
                '#title' => t('Name'),
                '#required' => TRUE,
                '#default_value' => '',
                '#description' => 'Name of category',
                '#size' => 20,
                '#maxlength' => 20,
            ),
            'submit' => array(
                '#type' => 'submit',
                '#value' => 'Add',
            ),
        ),
    );
}

function platform_add_category_form_submit($form, &$form_state)
{
    try
    {
        $id = platform_db_category_add($form_state['values']);
        drupal_set_message(
            'Added ' . $form_state['values']['name'] . ' ' .
            '(ID ' . $id . ')');
    }
    catch (Exception $e)
    {
        drupal_set_message($e->getMessage(), 'error');
    }
}

function platform_insert_product($node)
{
    if ($node->type != 'product')
    {
        return;
    }

    $product = platform_get_product($node);

    $id = platform_db_product_add($product);

    drupal_set_message(
            'Added ' . $product->title . ' ' .
            '(ID ' . $id . ')');

    platform_db_product_node($id, $node->nid);
}

function platform_update_product($node)
{
    $product = platform_get_product($node);
    $id = platform_db_product_id_get($node->nid);

    platform_db_product_edit($id, $product);

    drupal_set_message(
            'Updated ' . $product->title . ' ' .
            '(ID ' . $id . ')');
}

function platform_delete_product($node)
{
    $id = platform_db_product_id_get($node->nid);

    platform_db_product_node_remove($id, $node->nid);
    platform_db_product_remove($id);

    drupal_set_message(
            'Deleted the product ' .
            '(ID ' . $id . ')');
}

function platform_insert_news_post($node)
{
    $news_post = platform_get_news_post($node);

    $id = platform_db_news_post_add($news_post);

    drupal_set_message(
            'Added ' . $news_post->title . ' ' .
            '(ID ' . $id . ')');

    platform_db_news_post_node($id, $node->nid);
}

function platform_node_insert($node)
{
    try
    {
        switch($node->type)
        {
            case 'product':
                platform_insert_product($node);
                break;
            default:
                break;
        }
    }
    catch (Exception $e)
    {
        drupal_set_message($e->getMessage(), 'error');
    }
}

function platform_node_update($node)
{
    try
    {
        switch($node->type)
        {
            case 'product':
                platform_update_product($node);
                break;
            default:
                break;
        }
    }
    catch (Exception $e)
    {
        drupal_set_message($e->getMessage(), 'error');
    }
}

function platform_node_delete($node)
{
    try
    {
        switch($node->type)
        {
            case 'product':
                platform_delete_product($node);
                break;
            default:
                break;
        }
    }
    catch (Exception $e)
    {
        drupal_set_message($e->getMessage(), 'error');
    }
}
